const {createClient}=window.supabase;
const sb=createClient(window.ACADEMY_CONFIG.supabaseUrl,window.ACADEMY_CONFIG.supabasePublishableKey);
let user=null,profile=null,teacherCourses=[],studentCourses=[],selectedCourse=null,studentDayRows=[];
const $=id=>document.getElementById(id);
const msg=(id,text,error=true)=>{$(id).textContent=text||'';$(id).style.color=error?'var(--danger)':'var(--green)'};
const days=[['الأحد',0],['الاثنين',1],['الثلاثاء',2],['الأربعاء',3],['الخميس',4],['الجمعة',5],['السبت',6]];
const params=new URLSearchParams(location.search),inviteFromUrl=params.get('join');
if(inviteFromUrl)localStorage.setItem('qa_pending_join',inviteFromUrl);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const showToast=t=>{$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)};
const dayName=n=>days.find(d=>d[1]===n)?.[0]||n;
const today=()=>{const p=new Intl.DateTimeFormat('en',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).reduce((a,x)=>(a[x.type]=x.value,a),{});return `${p.year}-${p.month}-${p.day}`};
const dateObj=s=>new Date(`${s}T12:00:00`),iso=d=>d.toISOString().slice(0,10);
function setAuthMode(mode){$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode))}
function renderDaysChooser(){$('daysChooser').innerHTML=days.map(d=>`<label class="selected"><input type="checkbox" value="${d[1]}" checked><span>${d[0]}</span></label>`).join('');$('daysChooser').onchange=e=>{if(e.target.matches('input[type="checkbox"]'))e.target.closest('label').classList.toggle('selected',e.target.checked)}}
function courseDates(c){const out=[],start=dateObj(c.starts_on),end=dateObj(c.ends_on);for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){if((c.active_days||[]).includes(d.getDay())){const n=Math.floor((d-start)/86400000),date=iso(d);out.push({date,week:Math.floor(n/7)+1,day:d.getDay(),label:`الأسبوع ${Math.floor(n/7)+1} — ${dayName(d.getDay())}`})}}return out}
function fillDaySelect(select,entries,preferred,latestOnly=false){const list=latestOnly?entries.filter(x=>x.date<=today()):entries,usable=list.length?list:entries;select.innerHTML=usable.map(x=>`<option value="${x.date}">${x.label}</option>`).join('');const pick=preferred&&usable.some(x=>x.date===preferred)?preferred:(latestOnly?usable[usable.length-1]?.date:usable.find(x=>x.date>=today())?.date||usable[usable.length-1]?.date);if(pick)select.value=pick}
async function getProfile(){const r=await sb.from('qa_profiles').select('*').eq('id',user.id).single();if(r.error)throw r.error;return r.data}
async function joinPendingCourse(){const code=(localStorage.getItem('qa_pending_join')||'').trim();if(!code)return;if(profile.role==='teacher'){localStorage.removeItem('qa_pending_join');return}const r=await sb.rpc('qa_join_course',{p_code:code});if(!r.error){localStorage.removeItem('qa_pending_join');if(location.search)history.replaceState({},'',location.pathname)}else msg('globalMsg',r.error.message)}
async function openApp(){profile=await getProfile();await joinPendingCourse();$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('signOut').classList.remove('hidden');$('userName').textContent=profile.display_name;$('userRole').textContent=profile.role==='teacher'?'معلمة':'طالبة';if(profile.role==='teacher')await openTeacher();else await openStudent()}
async function openTeacher(){$('teacherView').classList.remove('hidden');$('studentView').classList.add('hidden');renderDaysChooser();$('teacherName').value=profile.display_name;$('courseWeeks').value=4;await loadTeacherCourses()}
async function loadTeacherCourses(){const r=await sb.from('qa_courses').select('*').order('created_at',{ascending:false});if(r.error)return msg('globalMsg',r.error.message);teacherCourses=r.data||[];$('createCourseCard').classList.toggle('hidden',teacherCourses.length>0);$('newCourseBtn').classList.toggle('hidden',teacherCourses.length===0);$('coursesList').innerHTML=teacherCourses.map(c=>`<div class="list-item ${selectedCourse?.id===c.id?'active':''}"><button data-course="${c.id}">${esc(c.title)}<small class="muted"> — ${esc(c.teacher_name)} · ${c.weeks_count||'?'} أسابيع</small></button></div>`).join('')||'<p class="hint">لم تنشئ دورة بعد.</p>';if(!selectedCourse&&teacherCourses[0])await selectTeacherCourse(teacherCourses[0].id)}
async function selectTeacherCourse(id){selectedCourse=teacherCourses.find(c=>c.id===id);if(!selectedCourse)return;$('teacherCoursePanel').classList.remove('hidden');$('teacherCourseTitle').textContent=selectedCourse.title;const link=`${location.origin}${location.pathname}?join=${encodeURIComponent(selectedCourse.invite_code||'')}`;$('inviteLink').value=link;fillDaySelect($('teacherDay'),courseDates(selectedCourse));await loadTeacherDay();await loadMembers();$('coursesList').querySelectorAll('.list-item').forEach(x=>x.classList.remove('active'));const active=$('coursesList').querySelector(`[data-course="${id}"]`)?.parentElement;if(active)active.classList.add('active')}
async function loadTeacherDay(){const date=$('teacherDay').value,r=await sb.from('qa_days').select('id,revision,locked,qa_tasks(id,title,position)').eq('course_id',selectedCourse.id).eq('day_date',date).maybeSingle(),rows=r.data?.qa_tasks||[];rows.sort((a,b)=>a.position-b.position);$('taskList').innerHTML=rows.map((t,i)=>`<div class="list-item"><span>${i+1}. ${esc(t.title)}</span></div>`).join('')||'<p class="hint">لا توجد مهام منشورة لهذا اليوم.</p>';await loadTeacherResults(r.data?.id,rows)}
async function loadTeacherResults(dayId,tasks){if(!dayId){$('resultsList').innerHTML='<p class="hint">انشر مهام اليوم أولاً لتظهر النتائج.</p>';return}const [mr,sr]=await Promise.all([sb.from('qa_members').select('user_id,qa_profiles(display_name)').eq('course_id',selectedCourse.id).eq('member_role','student').eq('active',true),sb.from('qa_submissions').select('student_id,task_ids').eq('day_id',dayId)]);if(mr.error||sr.error){$('resultsList').innerHTML='<p class="message">تعذر تحميل نتائج الطالبات.</p>';return}const saved=new Map((sr.data||[]).map(x=>[x.student_id,new Set(x.task_ids||[])])),total=tasks.length;$('resultsList').innerHTML=(mr.data||[]).map(m=>{const done=saved.get(m.user_id)?.size||0;return `<div class="list-item"><span>${esc(m.qa_profiles?.display_name||'طالبة')}</span><strong class="result-score">${done} من ${total}</strong></div>`}).join('')||'<p class="hint">لم تُضف طالبات إلى الدورة بعد.</p>'}
async function loadMembers(){const r=await sb.from('qa_members').select('user_id,member_role,active,qa_profiles(display_name)').eq('course_id',selectedCourse.id);$('membersList').innerHTML=(r.data||[]).map(m=>`<div class="list-item"><span>${esc(m.qa_profiles?.display_name||'حساب')}<small class="muted"> — ${m.member_role==='supervisor'?'مشرفة':'طالبة'}${m.active?'':' — موقوفة'}</small></span><button class="small-action" data-member="${m.user_id}" data-role="${m.member_role}" data-active="${m.active?'1':'0'}">${m.active?'إزالة':'إعادة'}</button></div>`).join('')||'<p class="hint">لا توجد عضويات بعد.</p>'}
async function openStudent(){$('studentView').classList.remove('hidden');$('teacherView').classList.add('hidden');const r=await sb.from('qa_members').select('course_id,qa_courses(id,title,starts_on,ends_on,active_days,weeks_count)').eq('user_id',user.id).eq('member_role','student').eq('active',true);studentCourses=(r.data||[]).map(x=>x.qa_courses).filter(Boolean);$('studentCourse').innerHTML=studentCourses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');if(studentCourses.length)await selectStudentCourse(studentCourses[0].id);else $('studentTasks').innerHTML='<p class="hint">افتحي رابط الدورة ثم سجّلي الدخول للانتساب تلقائياً.</p>'}
async function selectStudentCourse(id){const c=studentCourses.find(x=>x.id===id);if(!c)return;selectedCourse=c;const entries=courseDates(c).filter(x=>x.date<=today()),r=await sb.from('qa_days').select('id,day_date,revision,locked').eq('course_id',id).lte('day_date',today()).order('day_date',{ascending:false});studentDayRows=r.data||[];const byDate=new Map(studentDayRows.map(x=>[x.day_date,x])),visible=entries.filter(x=>byDate.has(x.date));$('studentDay').innerHTML=visible.map(x=>`<option value="${byDate.get(x.date).id}">${x.label}</option>`).join('');if(visible.length)$('studentDay').value=byDate.get(visible[visible.length-1].date).id;await loadStudentDay()}
async function loadStudentDay(){const d=studentDayRows.find(x=>x.id===$('studentDay').value);if(!d){$('studentTasks').innerHTML='<p class="hint">لا توجد مهام منشورة بعد.</p>';return}const [tr,sr]=await Promise.all([sb.from('qa_tasks').select('id,title,position').eq('day_id',d.id).order('position'),sb.from('qa_submissions').select('task_ids').eq('day_id',d.id).eq('student_id',user.id).maybeSingle()]),chosen=new Set(sr.data?.task_ids||[]);$('studentTasks').innerHTML=(tr.data||[]).map(t=>`<label class="task-check"><input type="checkbox" value="${t.id}" ${chosen.has(t.id)?'checked':''} ${d.locked?'disabled':''}><span>${esc(t.title)}</span></label>`).join('')||'<p class="hint">لا توجد مهام لهذا اليوم.</p>';$('saveStudent').disabled=d.locked}
async function login(e){e.preventDefault();msg('authMsg','');const r=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(r.error)return msg('authMsg',r.error.message);user=r.data.user;await openApp()}
async function signup(e){e.preventDefault();msg('authMsg','');const r=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{display_name:$('signupName').value.trim()}}});if(r.error)return msg('authMsg',r.error.message);msg('authMsg','تم إنشاء الحساب. سجّلي الدخول، وسيتم الانتساب للدورة تلقائياً إذا فتحتِ رابطها.',false)}
async function createCourse(e){e.preventDefault();const active=[...$('daysChooser').querySelectorAll('label.selected input')].map(x=>Number(x.value));if(!active.length)return showToast('اختاري يوماً واحداً على الأقل');const r=await sb.rpc('qa_create_course_v2',{p_title:$('courseTitle').value.trim(),p_teacher_name:$('teacherName').value.trim(),p_weeks:Number($('courseWeeks').value),p_days:active});if(r.error)return msg('globalMsg',r.error.message);$('courseForm').reset();$('teacherName').value=profile.display_name;$('createCourseCard').classList.add('hidden');await loadTeacherCourses();await selectTeacherCourse(r.data);showToast('تم إنشاء الدورة')}
async function publishTasks(){const titles=$('taskTitles').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!titles.length)return showToast('اكتب مهمة واحدة على الأقل');const r=await sb.rpc('qa_publish_tasks',{p_course:selectedCourse.id,p_date:$('teacherDay').value,p_titles:titles});if(r.error)return msg('globalMsg',r.error.message);$('taskTitles').value='';await loadTeacherDay();showToast('تم نشر المهام')}
async function addMember(e){e.preventDefault();const r=await sb.rpc('qa_set_member_by_email',{p_course:selectedCourse.id,p_email:$('memberEmail').value.trim(),p_role:$('memberRole').value,p_active:true});if(r.error)return msg('globalMsg',r.error.message);$('memberForm').reset();await loadMembers();showToast('تمت إضافة الحساب إلى الدورة')}
async function toggleMember(e){const b=e.target.closest('[data-member]');if(!b)return;const r=await sb.rpc('qa_set_member',{p_course:selectedCourse.id,p_user:b.dataset.member,p_role:b.dataset.role,p_active:b.dataset.active!=='1'});if(r.error)return msg('globalMsg',r.error.message);await loadMembers();showToast(b.dataset.active==='1'?'تمت إزالة الطالبة':'تمت إعادة الطالبة')}
async function saveStudent(){const d=studentDayRows.find(x=>x.id===$('studentDay').value);if(!d)return;const ids=[...document.querySelectorAll('#studentTasks input:checked')].map(x=>x.value),r=await sb.rpc('qa_save_day',{p_day:d.id,p_task_ids:ids,p_revision:d.revision});if(r.error)return msg('studentMsg',r.error.message);msg('studentMsg','تم حفظ إنجازك بنجاح.',false);showToast('تم الحفظ')}
async function printReport(kind){
  if(!selectedCourse)return;
  const selected=$('teacherDay').value,entry=courseDates(selectedCourse).find(x=>x.date===selected);if(!entry)return showToast('اختاري أسبوعاً ويومًا أولاً');
  const dates=courseDates(selectedCourse).filter(x=>kind==='week'?x.week===entry.week:x.date.slice(0,7)===selected.slice(0,7));
  const dr=await sb.from('qa_days').select('id,day_date,qa_tasks(id)').eq('course_id',selectedCourse.id).in('day_date',dates.map(x=>x.date));
  if(dr.error)return msg('globalMsg',dr.error.message);
  const dayRows=dr.data||[],dayIds=dayRows.map(x=>x.id);if(!dayIds.length)return showToast('لا توجد مهام منشورة في الفترة المحددة');
  const [mr,sr]=await Promise.all([sb.from('qa_members').select('user_id,qa_profiles(display_name)').eq('course_id',selectedCourse.id).eq('member_role','student').eq('active',true),sb.from('qa_submissions').select('day_id,student_id,task_ids').in('day_id',dayIds)]);
  if(mr.error||sr.error)return msg('globalMsg','تعذر تحميل بيانات التقرير');
  const submissions=sr.data||[],students=mr.data||[],rows=students.map(m=>{let done=0,total=0;for(const d of dayRows){total+=(d.qa_tasks||[]).length;const s=submissions.find(x=>x.day_id===d.id&&x.student_id===m.user_id);done+=(s?.task_ids||[]).length}return {name:m.qa_profiles?.display_name||'طالبة',done,total}});
  const title=kind==='week'?`تقرير الأسبوع ${entry.week}`:`تقرير الشهر ${selected.slice(0,7)}`;
  const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Tahoma,Arial,sans-serif;color:#172033;padding:24px}h1{text-align:center;color:#172554}p{text-align:center;color:#64748b}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #cbd5e1;padding:10px;text-align:center}th{background:#e0e7ff;color:#172554}.score{font-weight:bold;color:#172554}@media print{body{padding:0}}</style></head><body><h1>${esc(selectedCourse.title)} — ${title}</h1><p>المعلمة: ${esc(selectedCourse.teacher_name)} · تاريخ الطباعة: ${new Date().toLocaleDateString('ar-SA')}</p><table><thead><tr><th>#</th><th>اسم الطالبة</th><th>المهام المنجزة</th><th>النسبة</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td class="score">${r.done} من ${r.total}</td><td>${r.total?Math.round(r.done/r.total*100):0}%</td></tr>`).join('')||'<tr><td colspan="4">لا توجد طالبات</td></tr>'}</tbody></table><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),700)}<\/script></body></html>`;
  const w=window.open('','_blank');if(!w)return showToast('اسمحي بالنوافذ المنبثقة لإخراج التقرير');w.document.write(html);w.document.close();
}
async function copyInvite(){try{await navigator.clipboard.writeText($('inviteLink').value);showToast('تم نسخ رابط الانتساب')}catch{$('inviteLink').select();document.execCommand('copy');showToast('تم نسخ الرابط')}}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.auth)));$('loginForm').addEventListener('submit',login);$('signupForm').addEventListener('submit',signup);$('signOut').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});$('courseForm').addEventListener('submit',createCourse);$('publishTasks').addEventListener('click',publishTasks);$('memberForm').addEventListener('submit',addMember);$('membersList').addEventListener('click',toggleMember);$('studentCourse').addEventListener('change',e=>selectStudentCourse(e.target.value));$('studentDay').addEventListener('change',loadStudentDay);$('saveStudent').addEventListener('click',saveStudent);$('teacherDay').addEventListener('change',loadTeacherDay);$('coursesList').addEventListener('click',e=>{const b=e.target.closest('[data-course]');if(b)selectTeacherCourse(b.dataset.course)});$('copyInvite').addEventListener('click',copyInvite);$('printWeek').addEventListener('click',()=>printReport('week'));$('printMonth').addEventListener('click',()=>printReport('month'));$('newCourseBtn').addEventListener('click',()=>{$('createCourseCard').classList.remove('hidden');$('newCourseBtn').classList.add('hidden');$('courseTitle').focus()});
sb.auth.getSession().then(({data})=>{if(data.session){user=data.session.user;openApp().catch(e=>msg('globalMsg',e.message))}});
