const {createClient}=window.supabase;const sb=createClient(window.ACADEMY_CONFIG.supabaseUrl,window.ACADEMY_CONFIG.supabasePublishableKey);let user=null,profile=null,teacherCourses=[],studentCourses=[],selectedCourse=null,studentDayRows=[];
const $=id=>document.getElementById(id),msg=(id,text,error=true)=>{$(id).textContent=text||'';$(id).style.color=error?'var(--danger)':'var(--green)'};
const days=[['الأحد',0],['الاثنين',1],['الثلاثاء',2],['الأربعاء',3],['الخميس',4],['الجمعة',5],['السبت',6]];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function showToast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)}
function setAuthMode(mode){$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode))}
function dayName(n){return days.find(d=>d[1]===n)?.[0]||n}function today(){return new Date().toISOString().slice(0,10)}
async function getProfile(){const r=await sb.from('qa_profiles').select('*').eq('id',user.id).single();if(r.error)throw r.error;return r.data}
async function openApp(){profile=await getProfile();$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('signOut').classList.remove('hidden');$('userName').textContent=profile.display_name;$('userRole').textContent=profile.role==='teacher'?'معلمة':'طالبة';if(profile.role==='teacher'){await openTeacher()}else await openStudent()}
async function openTeacher(){$('teacherView').classList.remove('hidden');$('studentView').classList.add('hidden');$('daysChooser').innerHTML=days.map(d=>`<label><input type="checkbox" value="${d[1]}" checked><span>${d[0]}</span></label>`).join('');$('courseStart').value=today();$('courseEnd').value=today();await loadTeacherCourses()}
async function loadTeacherCourses(){const r=await sb.from('qa_courses').select('*').order('created_at',{ascending:false});if(r.error)return msg('globalMsg',r.error.message);teacherCourses=r.data||[];$('coursesList').innerHTML=teacherCourses.map(c=>`<div class="list-item ${selectedCourse?.id===c.id?'active':''}"><button data-course="${c.id}">${esc(c.title)}<small class="muted"> — ${esc(c.teacher_name)}</small></button></div>`).join('')||'<p class="hint">لم تنشئ دورة بعد.</p>'}
async function selectTeacherCourse(id){selectedCourse=teacherCourses.find(c=>c.id===id);if(!selectedCourse)return;$('teacherCoursePanel').classList.remove('hidden');$('teacherCourseTitle').textContent=selectedCourse.title;const opts=[];const start=new Date(selectedCourse.starts_on),end=new Date(selectedCourse.ends_on);for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){if(selectedCourse.active_days.includes(d.getDay()))opts.push(`<option value="${d.toISOString().slice(0,10)}">${d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'})}</option>`)}$('teacherDay').innerHTML=opts.join('');await loadTeacherDay();await loadMembers()}
async function loadTeacherDay(){const date=$('teacherDay').value;const r=await sb.from('qa_days').select('id,revision,locked,qa_tasks(id,title,position)').eq('course_id',selectedCourse.id).eq('day_date',date).maybeSingle();const rows=r.data?.qa_tasks||[];rows.sort((a,b)=>a.position-b.position);$('taskList').innerHTML=rows.map((t,i)=>`<div class="list-item"><span>${i+1}. ${esc(t.title)}</span></div>`).join('')||'<p class="hint">لا توجد مهام منشورة لهذا اليوم.</p>';await loadTeacherResults(r.data?.id,rows)}
async function loadTeacherResults(dayId,tasks){if(!dayId){$('resultsList').innerHTML='<p class="hint">انشر مهام اليوم أولاً لتظهر النتائج.</p>';return}const [mr,sr]=await Promise.all([sb.from('qa_members').select('user_id,qa_profiles(display_name)').eq('course_id',selectedCourse.id).eq('member_role','student').eq('active',true),sb.from('qa_submissions').select('student_id,task_ids').eq('day_id',dayId)]);if(mr.error||sr.error){$('resultsList').innerHTML='<p class="message">تعذر تحميل نتائج الطالبات.</p>';return}const saved=new Map((sr.data||[]).map(x=>[x.student_id,new Set(x.task_ids||[])]));const total=tasks.length;$('resultsList').innerHTML=(mr.data||[]).map(m=>{const done=saved.get(m.user_id)?.size||0;return `<div class="list-item"><span>${esc(m.qa_profiles?.display_name||'طالبة')}</span><strong class="result-score">${done} من ${total}</strong></div>`}).join('')||'<p class="hint">لم تُضف طالبات إلى الدورة بعد.</p>'}
async function loadMembers(){const r=await sb.from('qa_members').select('user_id,member_role,active,qa_profiles(display_name)').eq('course_id',selectedCourse.id);$('membersList').innerHTML=(r.data||[]).map(m=>`<div class="list-item"><span>${esc(m.qa_profiles?.display_name||'حساب')}</span><small class="muted">${m.member_role==='supervisor'?'مشرفة':'طالبة'}${m.active?'':' — موقوفة'}</small></div>`).join('')||'<p class="hint">لا توجد عضويات بعد.</p>'}
async function openStudent(){ $('studentView').classList.remove('hidden');$('teacherView').classList.add('hidden');const r=await sb.from('qa_members').select('course_id,qa_courses(id,title,starts_on,ends_on,active_days)').eq('user_id',user.id).eq('member_role','student').eq('active',true);studentCourses=(r.data||[]).map(x=>x.qa_courses).filter(Boolean);$('studentCourse').innerHTML=studentCourses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');if(studentCourses.length)await selectStudentCourse(studentCourses[0].id);else $('studentTasks').innerHTML='<p class="hint">لم تُضف إلى دورة بعد. أرسلي بريد حسابك للمعلمة.</p>'}
async function selectStudentCourse(id){const c=studentCourses.find(x=>x.id===id);if(!c)return;selectedCourse=c;const r=await sb.from('qa_days').select('id,day_date,revision,locked').eq('course_id',id).lte('day_date',today()).order('day_date',{ascending:false});studentDayRows=r.data||[];$('studentDay').innerHTML=studentDayRows.map(d=>`<option value="${d.id}">${new Date(d.day_date+'T12:00:00').toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'})}</option>`).join('');await loadStudentDay()}
async function loadStudentDay(){const d=studentDayRows.find(x=>x.id===$('studentDay').value);if(!d){$('studentTasks').innerHTML='<p class="hint">لا توجد مهام منشورة بعد.</p>';return}const [tr,sr]=await Promise.all([sb.from('qa_tasks').select('id,title,position').eq('day_id',d.id).order('position'),sb.from('qa_submissions').select('task_ids').eq('day_id',d.id).eq('student_id',user.id).maybeSingle()]);const chosen=new Set(sr.data?.task_ids||[]);$('studentTasks').innerHTML=(tr.data||[]).map(t=>`<label class="task-check"><input type="checkbox" value="${t.id}" ${chosen.has(t.id)?'checked':''} ${d.locked?'disabled':''}><span>${esc(t.title)}</span></label>`).join('')||'<p class="hint">لا توجد مهام لهذا اليوم.</p>';$('saveStudent').disabled=d.locked}
async function login(e){e.preventDefault();msg('authMsg','');const r=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(r.error)return msg('authMsg',r.error.message);user=r.data.user;await openApp()}
async function signup(e){e.preventDefault();msg('authMsg','');const r=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{display_name:$('signupName').value.trim()}}});if(r.error)return msg('authMsg',r.error.message);msg('authMsg','تم إنشاء الحساب. إذا ظهر طلب تأكيد البريد، افتح الرسالة ثم سجّل الدخول.',false)}
async function createCourse(e){e.preventDefault();const active=[...document.querySelectorAll('#daysChooser input:checked')].map(x=>Number(x.value));const r=await sb.rpc('qa_create_course',{p_title:$('courseTitle').value.trim(),p_teacher_name:$('teacherName').value.trim(),p_start:$('courseStart').value,p_end:$('courseEnd').value,p_days:active});if(r.error)return msg('globalMsg',r.error.message);$('courseForm').reset();await loadTeacherCourses();showToast('تم إنشاء الدورة')}
async function publishTasks(){const titles=$('taskTitles').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!titles.length)return showToast('اكتب مهمة واحدة على الأقل');const r=await sb.rpc('qa_publish_tasks',{p_course:selectedCourse.id,p_date:$('teacherDay').value,p_titles:titles});if(r.error)return msg('globalMsg',r.error.message);$('taskTitles').value='';await loadTeacherDay();showToast('تم نشر المهام')}
async function addMember(e){e.preventDefault();const r=await sb.rpc('qa_set_member_by_email',{p_course:selectedCourse.id,p_email:$('memberEmail').value.trim(),p_role:$('memberRole').value,p_active:true});if(r.error)return msg('globalMsg',r.error.message);$('memberForm').reset();await loadMembers();showToast('تمت إضافة الحساب إلى الدورة')}
async function saveStudent(){const d=studentDayRows.find(x=>x.id===$('studentDay').value);if(!d)return;const ids=[...document.querySelectorAll('#studentTasks input:checked')].map(x=>x.value);const r=await sb.rpc('qa_save_day',{p_day:d.id,p_task_ids:ids,p_revision:d.revision});if(r.error)return msg('studentMsg',r.error.message);msg('studentMsg','تم حفظ إنجازك بنجاح.',false);showToast('تم الحفظ')}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.auth)));$('loginForm').addEventListener('submit',login);$('signupForm').addEventListener('submit',signup);$('signOut').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});$('courseForm').addEventListener('submit',createCourse);$('publishTasks').addEventListener('click',publishTasks);$('memberForm').addEventListener('submit',addMember);$('studentCourse').addEventListener('change',e=>selectStudentCourse(e.target.value));$('studentDay').addEventListener('change',loadStudentDay);$('saveStudent').addEventListener('click',saveStudent);$('teacherDay').addEventListener('change',loadTeacherDay);$('coursesList').addEventListener('click',e=>{const b=e.target.closest('[data-course]');if(b)selectTeacherCourse(b.dataset.course)});
sb.auth.getSession().then(({data})=>{if(data.session){user=data.session.user;openApp().catch(e=>msg('globalMsg',e.message))}});
